# Generated by Django 6.0 on 2025-12-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image_url', models.CharField(default='https://i.imgur.com/rfxjQeS.png')),
                ('name', models.CharField()),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='api_user_email_a7eefd_idx')],
            },
        ),
    ]
