# Generated by Django 6.0 on 2025-12-26 03:52

import api.mixins.validate_on_save
import api.models.project
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Art', 'Art'), ('Fashion', 'Fashion'), ('Film', 'Film'), ('Food', 'Food'), ('Games', 'Games'), ('Technology', 'Technology')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(200)])),
                ('funding_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('funding_end_date', models.DateTimeField(help_text='Funding end date must be sometime within the next year', validators=[api.models.project.validate_min_date, api.models.project.validate_max_date])),
                ('image_url', models.URLField()),
                ('short_blurb', models.TextField(validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(135)])),
                ('title', models.CharField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(60)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='api_project_categor_6c424e_idx'), models.Index(fields=['funding_amount'], name='api_project_funding_ffed1c_idx'), models.Index(fields=['funding_end_date'], name='api_project_funding_9a661f_idx')],
            },
            bases=(api.mixins.validate_on_save.ValidateOnSaveMixin, models.Model),
        ),
    ]
