# Generated by Django 6.0 on 2025-12-26 04:29

import api.mixins.validate_on_save
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(default='')),
                ('title', models.CharField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'abstract': False,
            },
            bases=(api.mixins.validate_on_save.ValidateOnSaveMixin, models.Model),
        ),
    ]
