# Generated by Django 6.0 on 2025-12-26 13:57

import api.mixins.validate_on_save
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'reward'], name='api_backing_user_id_816c59_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'reward'), name='unique_user_reward')],
            },
            bases=(api.mixins.validate_on_save.ValidateOnSaveMixin, models.Model),
        ),
    ]
